version: '3.6'
services:
  backend:
    build: ./Backend
    restart: on-failure
    networks:
    - rpll
    volumes:
    - rpll_backend_storage:/Storage
    environment:
    - MYSQL_URL=mysql://legacyplayersv3prod:navglk6ynmd5dt4oiqi8py5jqpr3sqe5metcz56qs48r@legacyplayersv3prod.ckaemifzcfya.eu-west-1.rds.amazonaws.com/main
    - ROCKET_DATABASES={main={url="mysql://legacyplayersv3prod:navglk6ynmd5dt4oiqi8py5jqpr3sqe5metcz56qs48r@legacyplayersv3prod.ckaemifzcfya.eu-west-1.rds.amazonaws.com/main"}}
    - SMTP_DNS=127.0.0.1:25
    - HOST=http://localhost
    - MODEL_GENERATOR=http://localhost:5555
    - INSTANCE_STORAGE_PATH=/Storage

  webclient:
    build: ./Webclient
    restart: on-failure
    networks:
    - rpll

  reverse-proxy:
    build: ./ReverseProxy
    restart: on-failure
    networks:
    - rpll
    ports:
    - '80:80'

volumes:
  rpll_backend_storage:

networks:
  rpll: